# Generated by Django 4.2.4 on 2023-08-31 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_videos_content_videos_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='content',
            new_name='Content',
        ),
        migrations.RenameField(
            model_name='videos',
            old_name='title',
            new_name='Title',
        ),
    ]
