# Generated by Django 4.2.4 on 2023-08-31 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_content_videos_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='Content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='videos',
            old_name='Title',
            new_name='title',
        ),
    ]
